### ISSUE TITLE
Data source

### ISSUE THREAD

**Issue by EdwardBurgin** [pku-nlp-forfun/CWS_POS_NER#1]
Hi, am I correct in that the source of the dataset is not listed? Is the data a common dataset? How was the tagging performed?
Many thanks!

**Comment by iofu728** [comment]
Hi @EdwardBurgin, sorry just noticed this issue.
This repo was built on our school coursework project. You can find the data set in [Data](https://github.com/pku-nlp-forfun/CWS_POS_NER/tree/master/Data) folder.
